
ray:
  num_cpus: 6
  num_workers: 3

# Environment Settings
env:
  seed: 42
  physics_dt: 0.1
  device: "cuda"
  num_agent: 3
  max_velocity: 0.3
  max_yaw_rate: 1.0 # radians
  max_acceleration: 0.1

  fov: 120 # degrees
  sensor_range: 0.3 # meters
  num_rays: 61

  map:
    height: 1.0
    width: 5.0
    resolution: 0.01 
    map_representation:
      free: 0
      unknown: 1
      occupied: 2
      goal: 3
      start: 4
      frontier: 5

  controller:
    max_obs: 0
    max_agents: 0
    d_max: 0
    d_safe: 0
    a_max: 0
    w_max: 0
    v_max: 0
    gamma_c1: 2.5
    gamma_c2: 2.5
    gamma_a1: 1.5
    gamma_a2: 1.5
    gamma_conn1: 1.5
    gamma_conn2: 1.5
    w_slack: 1000

  curriculum:
    demo:
      demo_rate: 0.9
      start_rate: 0.9
      end_rate: 0.1
      


# Agent Settings
agent:
  mini_batch_size: 8
  max_batch_size: -1
  epoch: 4
  num_gae_block: 1

  discount_factor: 0.99
  gae_lambda: 0.95

  rotation_augmentation: 0

  value_clip_ratio: 0.2
  clip_ratio: 0.2
  grad_norm_clip: 0.5

  value_loss_coef: 0.5
  entropy_loss_coef: 0.005
  policy_loss_coef: 10.0

  buffer:
    rollout: 512

  experiment:
    directory: "MARL"
    experiment_name: ""
    write_interval: 5
    checkpoint_interval: 5

model:
  # Model Configuration
  model_type: gnn
  num_gnn_layer: 3
  use_history: true
  ablation: false

  # Optimizer Paramters
  actor_lr: 5e-4
  critic_lr: 5e-4
  eps: 1e-6
    
# Training Settings
train:
  eval_freq: 100
  max_episode: 1000
  timesteps: 5000000